### ISSUE TITLE
NeoHub v0.2.1 doesn't set proper working directory unless it's explicitly passed

### ISSUE THREAD

**Issue by alex35mil** [alex35mil/NeoHub#15]
When run `neohub@0.2.1` without any arguments, `neovide` starts at `$HOME` regardless of a cwd.

It happens only when I run `NeoHub.app` from outside Xcode.

Workarounds until I figure it out:
1. Provide path explicitly: `neohub .`
2. Run NeoHub from Xcode.

**Comment by alex35mil** [comment]
I just updated `neovim` to the latest stable and `neovide` to the latest master (`0.13.1`) and things work again. Closing this.

**Comment by unphased** [comment]
I'm a little bit confused, if the issue turns out isn't valid, could you update the releases entry for 0.2.1 so when we get there we aren't made to think that something's wrong with the release?
