### ISSUE TITLE
Add parameters

### ISSUE THREAD

**Issue by JensynLo** [alex35mil/NeoHub#17]
Can neohub use neovide's arguments? For example neovide --frame transparent

![image](https://github.com/alex35mil/NeoHub/assets/105597727/0890ca3e-5c1f-4acc-8bce-a17b3e9b2d32)

**Comment by falcucci** [comment]
Yep, just use the `--opts` command option to pass through it

```rust
neohub $PWD/$1 --opts --frame buttonless --no-fork --title-hidden --no-vsync --no-idle --no-tabs
```

**Comment by JensynLo** [comment]
> Yep, just use the `--opts` command option to pass through it
> 
> ```rust
> neohub $PWD/$1 --opts --frame buttonless --no-fork --title-hidden --no-vsync --no-idle --no-tabs
> ```

Thanks !
